[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "gage_rr_companion"
version = "0.1.0"
description = "This program is meant to act as a tool to assist in developing Gage R&R studies in an efficient manner."
readme = "README.md"
requires-python = ">=3.12"
license = {text = "BSD-3-Clause"}
authors = [
	{name = "Henry Nguyen", email = "nguyehen@uw.edu"},
	{name = "Logan Sayyadi", email = "lsayyadi@uw.edu"},
	{name = "Mason Keller", email = "masonk7@uw.edu"}
]
dependencies = [
	"altair>=6.0.0",
	"streamlit>=1.54.0",
	"pandas>=2.0.0",
	"numpy>=1.24.0",
	"statsmodels>=0.14.6",
	"dataclasses>=0.8",
]

[project.scripts]
gage_rr_companion = "gage_rr_companion.cli:main"

[tool.setuptools.packages.find]
where = ["src"]
